package com.q.model2;
// Generated 2017-10-16 11:22:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbImport generated by hbm2java
 */
@Entity
@Table(name = "tb_import", catalog = "conduct")
public class TbImport implements java.io.Serializable {

	private Long id;
	private TbUser tbUser;
	private Integer inputNum;
	private int statues;

	public TbImport() {
	}

	public TbImport(TbUser tbUser, int statues) {
		this.tbUser = tbUser;
		this.statues = statues;
	}

	public TbImport(TbUser tbUser, Integer inputNum, int statues) {
		this.tbUser = tbUser;
		this.inputNum = inputNum;
		this.statues = statues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Column(name = "inputNum")
	public Integer getInputNum() {
		return this.inputNum;
	}

	public void setInputNum(Integer inputNum) {
		this.inputNum = inputNum;
	}

	@Column(name = "statues", nullable = false)
	public int getStatues() {
		return this.statues;
	}

	public void setStatues(int statues) {
		this.statues = statues;
	}

}
