package com.q.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbOrder generated by hbm2java
 */
@Entity
@Table(name = "tb_order", catalog = "conduct")
public class TbOrder implements java.io.Serializable {

	private Long orderId;
	private TbUser tbUser;
	private Integer inputNum;
	private Integer outNum;
	private Integer orderStatues;

	public TbOrder() {
	}

	public TbOrder(TbUser tbUser, Integer inputNum, Integer outNum) {
		this.tbUser = tbUser;
		this.inputNum = inputNum;
		this.outNum = outNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orderId", unique = true, nullable = false)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Column(name = "inputNum")
	public Integer getInputNum() {
		return this.inputNum;
	}

	public void setInputNum(Integer inputNum) {
		this.inputNum = inputNum;
	}

	@Column(name = "outNum")
	public Integer getOutNum() {
		return this.outNum;
	}

	public void setOutNum(Integer outNum) {
		this.outNum = outNum;
	}

	@Column(name = "orderStatues")
	public Integer getOrderStatues() {
		return orderStatues;
	}

	public void setOrderStatues(Integer orderStatues) {
		this.orderStatues = orderStatues;
	}
	
}
