package com.q.model2;
// Generated 2017-10-16 11:22:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbOutput generated by hbm2java
 */
@Entity
@Table(name = "tb_output", catalog = "conduct")
public class TbOutput implements java.io.Serializable {

	private Long id;
	private TbUser tbUser;
	private Integer outputNum;
	private int statues;

	public TbOutput() {
	}

	public TbOutput(TbUser tbUser, int statues) {
		this.tbUser = tbUser;
		this.statues = statues;
	}

	public TbOutput(TbUser tbUser, Integer outputNum, int statues) {
		this.tbUser = tbUser;
		this.outputNum = outputNum;
		this.statues = statues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Column(name = "outputNum")
	public Integer getOutputNum() {
		return this.outputNum;
	}

	public void setOutputNum(Integer outputNum) {
		this.outputNum = outputNum;
	}

	@Column(name = "statues", nullable = false)
	public int getStatues() {
		return this.statues;
	}

	public void setStatues(int statues) {
		this.statues = statues;
	}

}
