package com.q.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbUser generated by hbm2java
 */
@Entity
@Table(name = "tb_user", catalog = "conduct")
public class TbUser implements java.io.Serializable {

	private Long id;
	private String name;
	private String password;
	private Integer balance;
	private int statues;
	private Set<TbOrder> tbOrders = new HashSet<TbOrder>(0);
	private String email;
	private String sex;

	public TbUser() {
	}

	public TbUser(String name, String password, Integer balance, int statues, Set<TbOrder> tbOrders) {
		this.name = name;
		this.password = password;
		this.balance = balance;
		this.statues = statues;
		this.tbOrders = tbOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "balance")
	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	@Column(name = "statues")
	public int getStatues() {
		return this.statues;
	}

	public void setStatues(int statues) {
		this.statues = statues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbOrder> getTbOrders() {
		return this.tbOrders;
	}

	public void setTbOrders(Set<TbOrder> tbOrders) {
		this.tbOrders = tbOrders;
	}

	@Column(name = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sex")
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
	
	
}
