package com.q.model;
// Generated 2017-10-16 11:22:22 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbUser generated by hbm2java
 */
@Entity
@Table(name = "tb_user", catalog = "conduct")
public class TbUser{

	private Long id;
	private String name;
	private String password;
	private Integer balance;
	private Integer statues;
	private String email;
	private String sex;
	private Set<Order> tbImports = new HashSet<Order>(0);

	public TbUser() {
	}

	public TbUser(String name, String password, Integer balance, Integer statues, String email, String sex,
			Set<Order> tbImports) {
		this.name = name;
		this.password = password;
		this.balance = balance;
		this.statues = statues;
		this.email = email;
		this.sex = sex;
		this.tbImports = tbImports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "balance")
	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	@Column(name = "statues")
	public Integer getStatues() {
		return this.statues;
	}

	public void setStatues(Integer statues) {
		this.statues = statues;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sex", length = 5)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<Order> getTbImports() {
		return this.tbImports;
	}

	public void setTbImports(Set<Order> tbImports) {
		this.tbImports = tbImports;
	}

}
